### ISSUE TITLE
How to remove endpoint related to upstream?

### ISSUE THREAD

**Issue by mwieczorek** [mwieczorek/gloo#1]
I created a new upstream plugin, a 'dummy' one, which returns always one endpoint for the new upstream type, with IP equal to `10.0.0.X`, where X = time.Now().Minute()

Every minute a new endpoint/IP is 'returned' from the plugin, but I don't know how to remove the old one from the 'cluster'

To recreate the issue:

- clone this repo
- `git switch dummy` # change branch to dummy
- `kind create cluster`
- `make push-kind-images`
- `glooctl install gateway`
- `kubectl set image deployment/gloo gloo=quay.io/solo-io/gloo:0.0.0-fork -n gloo-system`
- `kubectl apply -f install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml` # update CRDs to have new upstream def
- `kubectl create namespace dummy`
- kubectl apply file like below:

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: dummy
  namespace: dummy
spec:
  virtualHost:
    domains:
      - dummy.example.com
    routes:
      - matchers:
          - prefix: /
        options:
          autoHostRewrite: true
          prefixRewrite: /
        routeAction:
          single:
            upstream:
              name: dummy
              namespace: dummy
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: dummy
  namespace: dummy
spec:
  dummy:
    name: dummy

```

- check the cluster's endpoint like:

`glooctl proxy served-config | grep "clusterName: dummy" -A 30`

each minute, the list of endpoints gets a new item (the new one with 'current minute', but the old one is not removed).
If I delete gloo pod, the list gets once again only one endpoint (but after a minute there will be 2, another minute 3, and so on...)
